### ISSUE TITLE
I get an invalid currency error when trying to open solution in the

### ISSUE THREAD

**Issue by SantiFabre** [developerforce/troubleshoot-lwc#6]
![invalid currency](https://user-images.githubusercontent.com/46694501/124806089-b00e0600-df32-11eb-8eb3-dda23c57417e.PNG)

**Comment by Chantichi** [comment]
Same.

**Comment by MarkHMorrison** [comment]
We weren't able to duplicate the issue.  There is nothing dealing with currency in the module or examples.
